Vagrant.configure(2) do |config|
	config.vm.synced_folder '.', '/vagrant', disabled: true
	config.vm.box = "debian/contrib-jessie64"
	config.vm.network "private_network", ip: "192.89.116.1"
	config.vm.hostname = "bb.dev"
	config.hostsupdater.aliases = ["bb.dev"]
	config.vm.synced_folder "./bb/", "/srv/bb", create: true
	config.vm.synced_folder "./config/", "/var/config_files", create: true
	config.vm.provision :shell, path: "./config/bootstrap.sh"
	config.vm.provider "virtualbox" do |vb|
		vb.memory = "1024"
	end
end